# Generated by Django 4.2.1 on 2023-06-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='url_title',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='عنوان در url'),
        ),
    ]
