# Generated by Django 4.2.1 on 2023-06-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_productbrand_url_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbrand',
            name='url_title',
            field=models.CharField(db_index=True, max_length=300, verbose_name='عنوان در url'),
        ),
    ]
