# Generated by Django 4.2.1 on 2023-07-20 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_product_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/products_galery', verbose_name='تصویر محصول')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصوسر گالری محصول',
                'verbose_name_plural': 'گالری تصاویر محصولات ',
            },
        ),
    ]
