# Generated by Django 4.2.1 on 2023-07-29 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0002_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_module.order', verbose_name='سفارش مشتری'),
        ),
    ]
