# Generated by Django 4.2.1 on 2023-07-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0006_ads_baner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads_baner',
            name='image',
            field=models.ImageField(upload_to='images/ADS', verbose_name='تصویر تبلیغ'),
        ),
    ]
