# Generated by Django 4.2.1 on 2023-07-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0004_alter_userprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_user_for_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='ایمیل مخاطب ')),
            ],
        ),
    ]
