# Generated by Django 4.2.1 on 2023-08-27 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='add_email_for_off',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='ایمیل مخاطب برای خبر نامه ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده ')),
            ],
            options={
                'verbose_name': 'ایمیل خبرنامه',
                'verbose_name_plural': 'ایمیل ها برای خیرنامه',
            },
        ),
    ]
