# Generated by Django 4.2.1 on 2023-09-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add_email_for_off',
            options={'verbose_name': 'ایمیل خبرنامه', 'verbose_name_plural': 'ایمیل ها برای خبرنامه'},
        ),
        migrations.AlterField(
            model_name='add_email_for_off',
            name='email',
            field=models.EmailField(max_length=100, unique_for_date=True, verbose_name='ایمیل مخاطب برای خبر نامه '),
        ),
    ]
