# Generated by Django 4.2.1 on 2023-09-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0002_alter_add_email_for_off_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_email_for_off',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique_for_date=True, verbose_name='ایمیل مخاطب برای خبر نامه '),
        ),
    ]
