# Generated by Django 4.2.1 on 2023-09-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0003_alter_add_email_for_off_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_email_for_off',
            name='email',
            field=models.EmailField(default=True, max_length=100, verbose_name='ایمیل مخاطب برای خبر نامه '),
            preserve_default=False,
        ),
    ]
