# Generated by Django 4.2.1 on 2023-06-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(editable=False, max_length=100, verbose_name='کد فعالسازی ایمیل'),
        ),
    ]
